# Build settings
title: "Javier Pellejero Ortega"
description: "Javier Pellejero Ortega personal page"
url: "https://javpelle.github.io/"

markdown: kramdown
timezone: Europe/Berlin

#plugins:
#  - jemoji
#  - jekyll-feed
#  - jekyll-redirect-from